apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - apiGroups:
      - ""
    resources:
      - deployments
      - services
      - ingresses
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - "apiextensions.k8s.io"
      - "networking.istio.io"
      - "gateways.networking.k8s.io"
    resources:
      - customresourcedefinitions
      - virtualservices
      - gateways
    verbs:
        - '*'
  - apiGroups:
      - "org.example"
    resources:
      - operators
      - operators/status
      - operators/finalizers
    verbs:
     - "*"
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-account
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-rolebinding
subjects:
  - kind: ServiceAccount
    name: operator-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: operator-role
  apiGroup: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator-account
      containers:
        - name: operator
          image: operator:1.0